# Generated by Django 5.2.3 on 2025-07-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
