# Generated by Django 5.2.3 on 2025-07-29 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agency_average_rating_agency_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['-user__created_at'], 'verbose_name': 'Agency Profile', 'verbose_name_plural': 'Agency Profiles'},
        ),
        migrations.AlterModelOptions(
            name='tourist',
            options={'verbose_name': 'Tourist Profile', 'verbose_name_plural': 'Tourist Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(blank=True, choices=[('tour_operator', 'Tour Operator'), ('travel_agency', 'Travel Agency'), ('adventure_company', 'Adventure Company'), ('cultural_tours', 'Cultural Tours'), ('eco_tourism', 'Eco Tourism'), ('luxury_travel', 'Luxury Travel'), ('budget_travel', 'Budget Travel'), ('corporate_travel', 'Corporate Travel')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='operating_regions',
            field=models.JSONField(blank=True, default=list, help_text='Regions where agency operates'),
        ),
        migrations.AddField(
            model_name='agency',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media profiles'),
        ),
        migrations.AddField(
            model_name='agency',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='tourist',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='preferred_language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='tourist',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourist',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tourist',
            name='travel_budget_range',
            field=models.CharField(blank=True, help_text='e.g., $500-1000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='managed_guides',
            field=models.ManyToManyField(blank=True, related_name='agencies', to='core.guide'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='travel_interests',
            field=models.JSONField(blank=True, default=list, help_text='List of travel interests'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('agency', 'Agency'), ('admin', 'Admin')], default='tourist', max_length=20),
        ),
        migrations.AlterModelTable(
            name='agency',
            table='core_agency',
        ),
        migrations.AlterModelTable(
            name='tourist',
            table='core_tourist',
        ),
        migrations.AlterModelTable(
            name='user',
            table='core_user',
        ),
    ]
